### PR TITLE
PR

### PR DESCRIPTION
**Pull request by fgsoftware1**

### CODE REVIEW

**Comment by CCIGAMES** [comment]
@fgsoftware1 do you mind explaining what these big changes are?

**Comment by CCIGAMES** [comment]
Especially to @OneProblemAtATime

**Comment by fgsoftware1** [comment]
> @fgsoftware1 do you mind explaining what these big changes are?

I've reverted and sign everything but it seems like it requires a different ki da of signing(GPG)

about the changes, check discord I uploaded a vid or you can check my fork on github

Basically I got first game working

**Comment by CCIGAMES** [comment]
My discord account has been permanently disabled, so I can't check

**Pull request merged**
