### PR TITLE
AI?

### PR DESCRIPTION
**Pull request by fgsoftware1**

### CODE REVIEW

**Comment by CCIGAMES** [comment]
@OneProblemAtATime do you know what the issue is?

**Comment by CCIGAMES** [comment]
@fgsoftware1 what's going on with the pr?

**Comment by fgsoftware1** [comment]
> @fgsoftware1 what's going on with the pr?


merge is blocked, you have the main branch protected and all commits must be signed and i don't have access to repository settings anymore

**Comment by fgsoftware1** [comment]
@CCIGAMES even though i've amend with signing

**Comment by CCIGAMES** [comment]
@fgsoftware1 what was the commit?

**Comment by fgsoftware1** [comment]
> @fgsoftware1 what was the commit?

i'll try open anothe PR.
i've done BIGGGG! changes

**Comment by CCIGAMES** [comment]
What like?

**Pull request closed without merging**
